
const express= require('express')
const controllers = require('../controllers/note')
const userControllers = require('../controllers/user')
const messageControllers = require('../controllers/messages')
const router = express.Router()

router.get('/' , (req , res , next)=> {
    res.json("Notes Lelo!!!!")
})
router.get('/api' , (req , res , next)=> {
    res.json("Notes Lelo!!!")
})
router.delete('/api/users/deletehehehe/:userId', userControllers.deleteUser)
router.get('/api/notes', controllers.getAllNotes)
router.delete('/api/messages/:messageId' , messageControllers.deleteMessage)
router.get('/api/messages', messageControllers.getMessages)
router.post('/api/messages', messageControllers.createMessage)
router.get('/api/notes/:notesId' , controllers.getNotesById )
router.put('/api/edituser/:userId', userControllers.editUser)
router.post('/api/notes', controllers.createNotes)
router.delete('/api/notes/deletehehehe/:notesId' , controllers.deleteNotes)
router.post('/api/adminLogin', userControllers.loginAdmin)
router.patch('/api/notes/:notesId' , controllers.updateNotes)
router.post('/api/signup' , userControllers.signUp)
router.post('/api/login' , userControllers.login)
router.get('/api/users', userControllers.getUsers)
router.post('/api/socialLogin' , userControllers.socialLogin)
router.post('/api/socialRegister' , userControllers.socialRegister)
router.get('/api/notes/:course', controllers.getNotesByCourse)
router.get('/api/notes/:course/:semester' , controllers.getNotesBySemester)
router.get('/api/notes/:course/:semester/:subject', controllers.getNotesBySubject)
router.get('/api/notes/:course/:semester/:subject/:ctype', controllers.getNotesByType)
router.put('/api/likenote' , controllers.likeNote)
router.put('/api/dislikenote' , controllers.dislikeNote)
router.put('/api/clicknote' , controllers.clickNote)
module.exports = router
